package ex03.exception;

import java.io.IOException;
import java.util.Scanner;

public class MainEntryEx {
//	public static void main(String[] args) {
		/** 문제상황 */
//		System.out.println("x, y = ");
//		int x = 0, y = 0, result;
//		
//		x = new Scanner(System.in).nextInt();
//		y = new Scanner(System.in).nextInt();
//			
//		result = x / y; // 에러발생 상황
//		System.out.println(result);
		
		/** try catch 구문 */
//		try {
//			System.out.println("x, y = ");
//			int x = 0, y = 0, result;
//			
//			x = new Scanner(System.in).nextInt();
//			y = new Scanner(System.in).nextInt();
//				
//			result = x / y; // 에러발생 상황
//			System.out.println(result);	
//		} catch (Exception e) {
//			System.out.println("0으로 나눌 수 없습니다.");
//			System.out.println(e.getMessage());
//			e.printStackTrace();
//		}
		
		
		/** throws 위임 */
		// 구체적 예외는 , 로 나열 | Exception 만 쓰면 모두
		public static void main(String[] args) throws Exception, IOException { // 예외처리 위임
			
			
		
		
		}
		
//	}
}